name = "drcv-tunnel-server"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV 스토리지 바인딩
[[kv_namespaces]]
binding = "TUNNEL_MAPPINGS"
id = "b89da5d6ce3140cb86afcea9dec16766" # wrangler kv:namespace create 후 업데이트

# 환경 변수 (secrets로 설정)
# wrangler secret put CLOUDFLARE_ZONE_ID
# wrangler secret put CLOUDFLARE_API_TOKEN

[triggers]
crons = ["0 */6 * * *"] # 6시간마다 만료된 DNS 레코드 정리